baseurl: /sfd2013

markdown:         rdiscount
pygments:         true
paginate:         4

title:            SFD 2013
url:              http://qdlug.github.io/sfd2013
author:
    name:         SimonMYSun
    email:        simonmysun@gmail.com
<<<<<<< HEAD
    description:  "Simon MY Sun"
=======
    description:  "SFD 2013"
>>>>>>> 2ba568a111ea3a215ea4e952a47a8bab6704c813

about:            "Software Freedom Day"
follow:
    email:        simonmysun@gmail.com
    github:       https://github.com/simonmysun
    twitter:      http://www.twitter.com/simonmysun
    google:       https://plus.google.com/116961333351449443401
    facebook:     https://facebook.com/simonmysun
description:      SFD

indexContent:     true
imageLink:        http://hdn.xnimg.cn/photos/hdn521/20130620/2210/h_large_j3zZ_b2f5000005b1113e.jpg


style:            /css/style.css
blogName:         SFD 2013
blogDesc:         SFD 2013
favicon:          /favicon.ico
<<<<<<< HEAD

copyright:        Copyright © 2011-2012 MYSun All rights reserved.
=======
>>>>>>> 2ba568a111ea3a215ea4e952a47a8bab6704c813
